// <auto-generated />
using Mediafy.Checkout.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediafy.Checkout.DataAccess.Migrations
{
    [DbContext(typeof(MediafyInMemoryContext))]
    partial class MediafyInMemoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Mediafy.Checkout.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = 1,
                            Name = "10 nr 169 kr, spara 57%",
                            Price = 169m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Country = 2,
                            Name = "13 nr 399 kr, spar 53%",
                            Price = 99m,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            Country = 3,
                            Name = "24 nro 39 €, säästä 46%",
                            Price = 39m,
                            ProductId = 6
                        });
                });

            modelBuilder.Entity("Mediafy.Checkout.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "Sveriges största veckotidning ger dig glädje och inspiration, varje vecka.",
                            ImageUrl = "https://bilder.tidningskungen.se/upl/normal500/allers-16-2023.jpg",
                            Name = "Allers"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Donald Duck er Norges mest kjente tegneserieutgivelse som kommer ut en gang i uken.",
                            ImageUrl = "https://bilder.bladkongen.no/upl/normal500/donald-duck--co-9-2022.jpg",
                            Name = "Donald Duck & Co"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kotiliesi on rakastettu naistenlehti, joka tuo iloa ja väriä arkeen.",
                            ImageUrl = "https://kuvat.lehtiapaja.fi/upl/normal500/kotiliesi-10-2023.jpg",
                            Name = "Kotiliesi"
                        });
                });

            modelBuilder.Entity("Mediafy.Checkout.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Mediafy.Checkout.Domain.Entities.Product", "Product")
                        .WithMany("Offers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mediafy.Checkout.Domain.Entities.Product", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
